services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432" # 💡 ฝั่งซ้าย 5433 สำหรับให้เราใช้ pgAdmin เข้าจากข้างนอก
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://myuser:mypassword@postgres_db:5432/mydatabase
      - JWT_SECRET=supersecretkey123
      - LINE_CHANNEL_SECRET=537314e42d2001e33beb278725f25ed7
      - LINE_CHANNEL_ACCESS_TOKEN=2QlKCg+BeINN4rQzE8TBz5hnR1C2mfkvpWUnj/FoytUvXUF0MXdoMWoYiHYVajo3StwQy3EP+U1XD+dM/OKq0EDuELgUfExmetGAcuib8wN5iE0dWZUGPawDtpn5FzIJlbK9+yKeFzBpnJP6bqsSzgdB04t89/1O/w1cDnyilFU=
      - NEXT_PUBLIC_LIFF_ID=2010617243-H2wIcDTp
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres_db

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_LIFF_ID=2010617243-H2wIcDTp
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  pgdata:
